language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

allow_failures:
  - python: 3.2
  - python: 3.3

install: "pip install -Ur requirements.txt --use-mirrors"

script: "py.test -vs --pep8 --cov upaas"
