language: python

python:
  - 2.6
  - 2.7
  - 3.3

install:
  - pip install -Ur requirements.txt
  - pip install -Ur requirements-test.txt

script:
  - coverage run --rcfile=.coveragerc `which py.test` -vs --pep8

after_success:
  - coveralls

services:
  - mongodb
