language: python

python:
  - 2.6
  - 2.7

install:
  - pip install -Ur requirements.txt --use-mirrors --download-cache $HOME/.pip-cache
  - pip install -Ur requirements-test.txt --use-mirrors --download-cache $HOME/.pip-cache

script: "py.test -vs --pep8 --cov upaas"

services:
  - mongodb

cache:
  directories:
    - $HOME/.pip-cache/
