# uPaaS configuration


mongodb:
  # mongodb database settings
  host: localhost
  database: upaas
  username: upaas
  password: upaasdev


paths:
  # where to store app files during package build
  workdir: /var/upaas/workdir


storage:
  # class implementing storage access
  handler: upaas.storage.local.LocalStorage
  settings:
    dir: /var/upaas/storage


# commands used to create empty system image
# variables:
# %workdir% - chroot directory that should be created
bootstrap:
  timelimit: 600
  # envs are optional
  env:
    http_proxy: http://localhost:3128/
    LC_ALL: C
    LANG: C
  commands:
    - debootstrap --components=main,universe,multiverse,restricted `lsb_release -sc` %workdir%


commands:
  # how long any action command can take to execute
  timelimit: 600
  # how to install or remove package
  install:
    env:
      http_proxy: http://localhost:3128/
      DEBIAN_FRONTEND: noninteractive
      LC_ALL: C
      LANG: C
    cmd: apt-get install --no-install-recommends -y %package%
  uninstall:
    env:
      DEBIAN_FRONTEND: noninteractive
      LC_ALL: C
      LANG: C
    cmd: apt-get remove -y %package%


apps:
  # name or uid of user that will be used to run app inside namespace
  uid: www-data
  # name or gid of group that will be used to run app inside namespace
  gid: www-data


interpreters:

  env:
    LC_ALL: C
    LANG: C

  packages:
    - build-essential

  actions:
    setup:
      system:
        - echo "#!/bin/sh\n" > /usr/sbin/policy-rc.d
        - echo "exit 101\n" >> /usr/sbin/policy-rc.d
        - chmod 755 /usr/sbin/policy-rc.d
        - apt-get update
        - apt-get dist-upgrade -y
      finalize:
        - apt-get clean

  ruby:
    any:
      env:
        RAILS_ENV: production
      actions:
        setup:
          main:
            - gem install bundler
            - bundle install --deployment --without test development
    1.8.7:
      plugin: rack187
      packages:
        - ruby1.8
        - ruby1.8-dev
        - rubygems
    1.9.3:
      plugin: rack193
      packages:
        - ruby1.9.1
        - ruby1.9.1-dev
      actions:
        setup:
          interpreter:
            - update-alternatives --force --install /usr/bin/gem gem /usr/bin/gem1.9.1 400
            - update-alternatives --force --install /usr/bin/ruby ruby /usr/bin/ruby1.9.1 400 --slave /usr/bin/ri ri /usr/bin/ri1.9.1 --slave /usr/bin/irb irb /usr/bin/irb1.9.1
            - ruby -v


  python:

    2.7:
      plugin: python27
      packages:
        - python2.7
        - python2.7-dev
        - python-pip
      actions:
        setup:
          main:
            - pip install -qMU -r requirements.txt
    3.2:
      plugin: python32
      packages:
        - python3.2
        - python3.2-dev
        - python3-pip
      actions:
        setup:
          main:
            - pip-3.2 install -qMU -r requirements.txt

  php:
    5.3:
      plugin: php53
      packages:
        - php5-dev
        - php-pear


uwsgi:
  options:
    autoload: true
    plugins-dir: /usr/local/lib/uwsgi
